spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seckill2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 50
    minIdle: 250
    maxActive: 500
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  resources:
    add-mappings: true
    cache:
      period: 3600s
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/


mybatis:
#加了此配置会让配置类MyBatisConfig失效
#  config-location: classpath:mybatis/mybatis-config.xml #指定全局配置文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml  #指定sql映射文件的位置
  type-aliases-package: com.lucq.seckill.domain #与数据库表对应类所在的包
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    # 下划线与驼峰命名法转换规则
    map-underscore-to-camel-case: true





